[Telegram]
# Telegram Bot Token
bot_token = "YOUR_TELEGRAM_BOT_TOKEN_HERE"

[Database]
# 数据库连接信息
host = "127.0.0.1"
port = 3306
user = "your_username"
password = "your_password"
dbname = "your_database_name"
